// 定义项目 API 的 proto 文件 可以同时描述 gRPC 和 HTTP API
// protobuf 文件参考:
//  - https://developers.google.com/protocol-buffers/

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: event.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KVPut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=Val,proto3" json:"Val,omitempty"`
}

func (x *KVPut) Reset() {
	*x = KVPut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVPut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPut) ProtoMessage() {}

func (x *KVPut) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPut.ProtoReflect.Descriptor instead.
func (*KVPut) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *KVPut) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVPut) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type NamespacePut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=Val,proto3" json:"Val,omitempty"`
}

func (x *NamespacePut) Reset() {
	*x = NamespacePut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamespacePut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespacePut) ProtoMessage() {}

func (x *NamespacePut) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespacePut.ProtoReflect.Descriptor instead.
func (*NamespacePut) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *NamespacePut) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *NamespacePut) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type ServicePut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=Val,proto3" json:"Val,omitempty"`
}

func (x *ServicePut) Reset() {
	*x = ServicePut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServicePut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePut) ProtoMessage() {}

func (x *ServicePut) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePut.ProtoReflect.Descriptor instead.
func (*ServicePut) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *ServicePut) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ServicePut) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type UserAdd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	User     string `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *UserAdd) Reset() {
	*x = UserAdd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAdd) ProtoMessage() {}

func (x *UserAdd) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAdd.ProtoReflect.Descriptor instead.
func (*UserAdd) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *UserAdd) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UserAdd) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UserAdd) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RoleAdd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role string `protobuf:"bytes,1,opt,name=Role,proto3" json:"Role,omitempty"`
}

func (x *RoleAdd) Reset() {
	*x = RoleAdd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAdd) ProtoMessage() {}

func (x *RoleAdd) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAdd.ProtoReflect.Descriptor instead.
func (*RoleAdd) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *RoleAdd) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UserGrantRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Role string `protobuf:"bytes,2,opt,name=Role,proto3" json:"Role,omitempty"`
}

func (x *UserGrantRole) Reset() {
	*x = UserGrantRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGrantRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGrantRole) ProtoMessage() {}

func (x *UserGrantRole) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGrantRole.ProtoReflect.Descriptor instead.
func (*UserGrantRole) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *UserGrantRole) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UserGrantRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RoleGrantPermission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role string `protobuf:"bytes,1,opt,name=Role,proto3" json:"Role,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Perm int32  `protobuf:"varint,3,opt,name=Perm,proto3" json:"Perm,omitempty"`
}

func (x *RoleGrantPermission) Reset() {
	*x = RoleGrantPermission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGrantPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGrantPermission) ProtoMessage() {}

func (x *RoleGrantPermission) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGrantPermission.ProtoReflect.Descriptor instead.
func (*RoleGrantPermission) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *RoleGrantPermission) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RoleGrantPermission) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RoleGrantPermission) GetPerm() int32 {
	if x != nil {
		return x.Perm
	}
	return 0
}

type NamespaceDel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *NamespaceDel) Reset() {
	*x = NamespaceDel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamespaceDel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceDel) ProtoMessage() {}

func (x *NamespaceDel) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceDel.ProtoReflect.Descriptor instead.
func (*NamespaceDel) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *NamespaceDel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ServiceDel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *ServiceDel) Reset() {
	*x = ServiceDel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDel) ProtoMessage() {}

func (x *ServiceDel) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDel.ProtoReflect.Descriptor instead.
func (*ServiceDel) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceDel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type UserDel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
}

func (x *UserDel) Reset() {
	*x = UserDel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDel) ProtoMessage() {}

func (x *UserDel) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDel.ProtoReflect.Descriptor instead.
func (*UserDel) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *UserDel) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type RoleDel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role string `protobuf:"bytes,1,opt,name=Role,proto3" json:"Role,omitempty"`
}

func (x *RoleDel) Reset() {
	*x = RoleDel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleDel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDel) ProtoMessage() {}

func (x *RoleDel) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDel.ProtoReflect.Descriptor instead.
func (*RoleDel) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{10}
}

func (x *RoleDel) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*Event_KvPut
	//	*Event_NamespacePut
	//	*Event_ServicePut
	//	*Event_UserAdd
	//	*Event_RoleAdd
	//	*Event_UserGrantRole
	//	*Event_RoleGrantPermission
	//	*Event_NamespaceDel
	//	*Event_ServiceDel
	//	*Event_UserDel
	//	*Event_RoleDel
	Payload isEvent_Payload `protobuf_oneof:"payload"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{11}
}

func (m *Event) GetPayload() isEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Event) GetKvPut() *KVPut {
	if x, ok := x.GetPayload().(*Event_KvPut); ok {
		return x.KvPut
	}
	return nil
}

func (x *Event) GetNamespacePut() *NamespacePut {
	if x, ok := x.GetPayload().(*Event_NamespacePut); ok {
		return x.NamespacePut
	}
	return nil
}

func (x *Event) GetServicePut() *ServicePut {
	if x, ok := x.GetPayload().(*Event_ServicePut); ok {
		return x.ServicePut
	}
	return nil
}

func (x *Event) GetUserAdd() *UserAdd {
	if x, ok := x.GetPayload().(*Event_UserAdd); ok {
		return x.UserAdd
	}
	return nil
}

func (x *Event) GetRoleAdd() *RoleAdd {
	if x, ok := x.GetPayload().(*Event_RoleAdd); ok {
		return x.RoleAdd
	}
	return nil
}

func (x *Event) GetUserGrantRole() *UserGrantRole {
	if x, ok := x.GetPayload().(*Event_UserGrantRole); ok {
		return x.UserGrantRole
	}
	return nil
}

func (x *Event) GetRoleGrantPermission() *RoleGrantPermission {
	if x, ok := x.GetPayload().(*Event_RoleGrantPermission); ok {
		return x.RoleGrantPermission
	}
	return nil
}

func (x *Event) GetNamespaceDel() *NamespaceDel {
	if x, ok := x.GetPayload().(*Event_NamespaceDel); ok {
		return x.NamespaceDel
	}
	return nil
}

func (x *Event) GetServiceDel() *ServiceDel {
	if x, ok := x.GetPayload().(*Event_ServiceDel); ok {
		return x.ServiceDel
	}
	return nil
}

func (x *Event) GetUserDel() *UserDel {
	if x, ok := x.GetPayload().(*Event_UserDel); ok {
		return x.UserDel
	}
	return nil
}

func (x *Event) GetRoleDel() *RoleDel {
	if x, ok := x.GetPayload().(*Event_RoleDel); ok {
		return x.RoleDel
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_KvPut struct {
	KvPut *KVPut `protobuf:"bytes,2,opt,name=kvPut,proto3,oneof"`
}

type Event_NamespacePut struct {
	NamespacePut *NamespacePut `protobuf:"bytes,3,opt,name=namespacePut,proto3,oneof"`
}

type Event_ServicePut struct {
	ServicePut *ServicePut `protobuf:"bytes,4,opt,name=servicePut,proto3,oneof"`
}

type Event_UserAdd struct {
	UserAdd *UserAdd `protobuf:"bytes,5,opt,name=userAdd,proto3,oneof"`
}

type Event_RoleAdd struct {
	RoleAdd *RoleAdd `protobuf:"bytes,6,opt,name=roleAdd,proto3,oneof"`
}

type Event_UserGrantRole struct {
	UserGrantRole *UserGrantRole `protobuf:"bytes,7,opt,name=userGrantRole,proto3,oneof"`
}

type Event_RoleGrantPermission struct {
	RoleGrantPermission *RoleGrantPermission `protobuf:"bytes,8,opt,name=roleGrantPermission,proto3,oneof"`
}

type Event_NamespaceDel struct {
	NamespaceDel *NamespaceDel `protobuf:"bytes,9,opt,name=namespaceDel,proto3,oneof"`
}

type Event_ServiceDel struct {
	ServiceDel *ServiceDel `protobuf:"bytes,10,opt,name=serviceDel,proto3,oneof"`
}

type Event_UserDel struct {
	UserDel *UserDel `protobuf:"bytes,11,opt,name=userDel,proto3,oneof"`
}

type Event_RoleDel struct {
	RoleDel *RoleDel `protobuf:"bytes,12,opt,name=roleDel,proto3,oneof"`
}

func (*Event_KvPut) isEvent_Payload() {}

func (*Event_NamespacePut) isEvent_Payload() {}

func (*Event_ServicePut) isEvent_Payload() {}

func (*Event_UserAdd) isEvent_Payload() {}

func (*Event_RoleAdd) isEvent_Payload() {}

func (*Event_UserGrantRole) isEvent_Payload() {}

func (*Event_RoleGrantPermission) isEvent_Payload() {}

func (*Event_NamespaceDel) isEvent_Payload() {}

func (*Event_ServiceDel) isEvent_Payload() {}

func (*Event_UserDel) isEvent_Payload() {}

func (*Event_RoleDel) isEvent_Payload() {}

var File_event_proto protoreflect.FileDescriptor

var file_event_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x2b, 0x0a, 0x05, 0x4b, 0x56, 0x50, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x56, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x56, 0x61, 0x6c, 0x22, 0x32,
	0x0a, 0x0c, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x50, 0x75, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x56, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x56,
	0x61, 0x6c, 0x22, 0x30, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x75, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b,
	0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x56, 0x61, 0x6c, 0x22, 0x4b, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x1d, 0x0a, 0x07, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x64, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x52, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65,
	0x22, 0x37, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x6f, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x4f, 0x0a, 0x13, 0x52, 0x6f, 0x6c,
	0x65, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x52, 0x6f, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x65, 0x72, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x65, 0x72, 0x6d, 0x22, 0x20, 0x0a, 0x0c, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x1e, 0x0a, 0x0a,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x1d, 0x0a, 0x07,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x22, 0x1d, 0x0a, 0x07, 0x52,
	0x6f, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0xb5, 0x04, 0x0a, 0x05, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x6b, 0x76, 0x50, 0x75, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x56, 0x50, 0x75, 0x74, 0x48, 0x00,
	0x52, 0x05, 0x6b, 0x76, 0x50, 0x75, 0x74, 0x12, 0x36, 0x0a, 0x0c, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x50, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x62, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x50, 0x75, 0x74, 0x48,
	0x00, 0x52, 0x0c, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x50, 0x75, 0x74, 0x12,
	0x30, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x75, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x50, 0x75, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x75,
	0x74, 0x12, 0x27, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x48,
	0x00, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x12, 0x27, 0x0a, 0x07, 0x72, 0x6f,
	0x6c, 0x65, 0x41, 0x64, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x64, 0x64, 0x48, 0x00, 0x52, 0x07, 0x72, 0x6f, 0x6c, 0x65,
	0x41, 0x64, 0x64, 0x12, 0x39, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x47, 0x72, 0x61, 0x6e, 0x74,
	0x52, 0x6f, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x48, 0x00, 0x52,
	0x0d, 0x75, 0x73, 0x65, 0x72, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x4b,
	0x0a, 0x13, 0x72, 0x6f, 0x6c, 0x65, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x13, 0x72, 0x6f, 0x6c, 0x65, 0x47, 0x72, 0x61, 0x6e,
	0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x0c, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x44, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x0c, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x44, 0x65, 0x6c, 0x12, 0x30, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65,
	0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x44, 0x65, 0x6c, 0x12, 0x27, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x44, 0x65, 0x6c,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x12, 0x27,
	0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x07,
	0x72, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x63, 0x61, 0x63,
	0x6f, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x69, 0x6e, 0x67, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData = file_event_proto_rawDesc
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_event_proto_rawDescData)
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_event_proto_goTypes = []interface{}{
	(*KVPut)(nil),               // 0: pb.KVPut
	(*NamespacePut)(nil),        // 1: pb.NamespacePut
	(*ServicePut)(nil),          // 2: pb.ServicePut
	(*UserAdd)(nil),             // 3: pb.UserAdd
	(*RoleAdd)(nil),             // 4: pb.RoleAdd
	(*UserGrantRole)(nil),       // 5: pb.UserGrantRole
	(*RoleGrantPermission)(nil), // 6: pb.RoleGrantPermission
	(*NamespaceDel)(nil),        // 7: pb.NamespaceDel
	(*ServiceDel)(nil),          // 8: pb.ServiceDel
	(*UserDel)(nil),             // 9: pb.UserDel
	(*RoleDel)(nil),             // 10: pb.RoleDel
	(*Event)(nil),               // 11: pb.Event
}
var file_event_proto_depIdxs = []int32{
	0,  // 0: pb.Event.kvPut:type_name -> pb.KVPut
	1,  // 1: pb.Event.namespacePut:type_name -> pb.NamespacePut
	2,  // 2: pb.Event.servicePut:type_name -> pb.ServicePut
	3,  // 3: pb.Event.userAdd:type_name -> pb.UserAdd
	4,  // 4: pb.Event.roleAdd:type_name -> pb.RoleAdd
	5,  // 5: pb.Event.userGrantRole:type_name -> pb.UserGrantRole
	6,  // 6: pb.Event.roleGrantPermission:type_name -> pb.RoleGrantPermission
	7,  // 7: pb.Event.namespaceDel:type_name -> pb.NamespaceDel
	8,  // 8: pb.Event.serviceDel:type_name -> pb.ServiceDel
	9,  // 9: pb.Event.userDel:type_name -> pb.UserDel
	10, // 10: pb.Event.roleDel:type_name -> pb.RoleDel
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVPut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamespacePut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServicePut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAdd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleAdd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGrantRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleGrantPermission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamespaceDel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleDel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_event_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*Event_KvPut)(nil),
		(*Event_NamespacePut)(nil),
		(*Event_ServicePut)(nil),
		(*Event_UserAdd)(nil),
		(*Event_RoleAdd)(nil),
		(*Event_UserGrantRole)(nil),
		(*Event_RoleGrantPermission)(nil),
		(*Event_NamespaceDel)(nil),
		(*Event_ServiceDel)(nil),
		(*Event_UserDel)(nil),
		(*Event_RoleDel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_rawDesc = nil
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
