// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/cacos-group/cacos/internal/conf"
	"github.com/cacos-group/cacos/internal/core/event/sourcing"
	"github.com/cacos-group/cacos/internal/core/query"
	"github.com/cacos-group/cacos/internal/logger"
	"github.com/cacos-group/cacos/internal/resource"
	"github.com/cacos-group/cacos/internal/server/grpc"
	"github.com/cacos-group/cacos/internal/service"
)

// Injectors from wire.go:

func InitApp(config *conf.Config) (*App, func(), error) {
	db, cleanup, err := resource.NewDB(config)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := resource.NewEtcd(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	queryClient := query.NewClient(db, client)
	sourcingClient := sourcing.NewClient(db, client)
	serviceService, cleanup3, err := service.New(queryClient, sourcingClient)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	zaplogLogger := logger.NewLog(config)
	server, cleanup4, err := grpc.New(config, zaplogLogger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app, cleanup5, err := NewApp(config, serviceService, server, zaplogLogger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
