[server]
name = ""
version = ""
port = 9090
timeout = "2s"

[etcd]
endpoints = ["127.0.0.1:2379"]
username = "root"
password = "root"

[mysql]
dsn = "admin:admin@tcp(127.0.01:3306)/cacos?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&charset=utf8mb4&loc=Local"
MaxOpenConns  = 100
MaxIdleConns  =  1
ConnMaxLifetime = "60s"
ConnMaxIdleTime = "60s"

[log]
logName = "./logs/cacos.log"